package com.zsubera.jpa.update;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.Test;

/**
 * MergeSpec 批量 UPSERT 与 @Embedded 字段混合 null/非null 的单元测试。
 *
 * <p>验证修复：当批次中首个实体的 @Embedded 字段为 null 而后续实体非 null 时，
 * 列名并集应包含所有可能的列，而非仅首个实体的列集。
 *
 * <p>此测试为纯单元测试，不需要数据库或 Spring 上下文。
 */
class MergeSpecBatchEmbeddedTest {

    @Embeddable
    static class Address {
        private String street;
        private String city;

        public Address() {}

        public Address(String street, String city) {
            this.street = street;
            this.city = city;
        }

        public String getStreet() { return street; }
        public void setStreet(String street) { this.street = street; }
        public String getCity() { return city; }
        public void setCity(String city) { this.city = city; }
    }

    @Entity
    @Table(name = "batch_embedded_entity")
    static class BatchEmbeddedEntity {
        @Id
        @GeneratedValue
        private Long id;

        private String name;

        @Embedded
        private Address address;

        public Long getId() { return id; }
        public void setId(Long id) { this.id = id; }
        public String getName() { return name; }
        public void setName(String name) { this.name = name; }
        public Address getAddress() { return address; }
        public void setAddress(Address address) { this.address = address; }
    }

    /**
     * P0-1 核心验证：模拟 doBatchMultiRow 的列收集逻辑，
     * 验证混合 null/非null @Embedded 时列名并集正确。
     */
    @Test
    void columnUnion_mixedNullEmbedded_containsAllColumns() {
        EntityFieldExtractor<BatchEmbeddedEntity> extractor =
            new EntityFieldExtractor<>(BatchEmbeddedEntity.class);

        // entity1: @Embedded 为 null
        BatchEmbeddedEntity e1 = new BatchEmbeddedEntity();
        e1.setName("Alice");
        e1.setAddress(null);
        List<EntityFieldExtractor.EntityFieldValue> fvs1 = extractor.extractFieldValues(e1);

        // entity2: @Embedded 非 null
        BatchEmbeddedEntity e2 = new BatchEmbeddedEntity();
        e2.setName("Bob");
        e2.setAddress(new Address("123 Main St", "NYC"));
        List<EntityFieldExtractor.EntityFieldValue> fvs2 = extractor.extractFieldValues(e2);

        // 模拟修复后的列收集逻辑：并集
        Set<String> allColumnsSet = new LinkedHashSet<>();
        for (EntityFieldExtractor.EntityFieldValue fv : fvs1) {
            if (fv.value() != null || !extractor.isAutoGeneratedId(fv.fieldName())) {
                allColumnsSet.add(fv.columnName());
            }
        }
        for (EntityFieldExtractor.EntityFieldValue fv : fvs2) {
            if (fv.value() != null || !extractor.isAutoGeneratedId(fv.fieldName())) {
                allColumnsSet.add(fv.columnName());
            }
        }

        // 验证并集包含所有列
        assertTrue(allColumnsSet.contains("name"), "Should contain 'name'");
        assertTrue(allColumnsSet.contains("street"), "Should contain 'street' from e2");
        assertTrue(allColumnsSet.contains("city"), "Should contain 'city' from e2");
        assertEquals(3, allColumnsSet.size(), "Should have 3 columns: name, street, city");
    }

    /**
     * 模拟修复前的逻辑：仅使用首个实体的列集，验证会丢失列。
     */
    @Test
    void columnSet_firstEntityOnly_missesColumns() {
        EntityFieldExtractor<BatchEmbeddedEntity> extractor =
            new EntityFieldExtractor<>(BatchEmbeddedEntity.class);

        // entity1: @Embedded 为 null
        BatchEmbeddedEntity e1 = new BatchEmbeddedEntity();
        e1.setName("Alice");
        e1.setAddress(null);
        List<EntityFieldExtractor.EntityFieldValue> fvs1 = extractor.extractFieldValues(e1);

        // entity2: @Embedded 非 null
        BatchEmbeddedEntity e2 = new BatchEmbeddedEntity();
        e2.setName("Bob");
        e2.setAddress(new Address("123 Main St", "NYC"));
        List<EntityFieldExtractor.EntityFieldValue> fvs2 = extractor.extractFieldValues(e2);

        // 模拟修复前的逻辑：仅使用首个实体的列集
        Set<String> firstEntityColumns = new LinkedHashSet<>();
        for (EntityFieldExtractor.EntityFieldValue fv : fvs1) {
            if (fv.value() != null || !extractor.isAutoGeneratedId(fv.fieldName())) {
                firstEntityColumns.add(fv.columnName());
            }
        }

        // 验证首个实体的列集缺少 address 子列
        assertTrue(firstEntityColumns.contains("name"), "Should contain 'name'");
        assertFalse(firstEntityColumns.contains("street"), "Should NOT contain 'street' (e1 has null embedded)");
        assertFalse(firstEntityColumns.contains("city"), "Should NOT contain 'city' (e1 has null embedded)");
        assertEquals(1, firstEntityColumns.size(), "Should have only 1 column: name");

        // 验证 e2 的列集包含 address 子列
        Set<String> secondEntityColumns = new LinkedHashSet<>();
        for (EntityFieldExtractor.EntityFieldValue fv : fvs2) {
            if (fv.value() != null || !extractor.isAutoGeneratedId(fv.fieldName())) {
                secondEntityColumns.add(fv.columnName());
            }
        }
        assertTrue(secondEntityColumns.contains("street"), "e2 should have 'street'");
        assertTrue(secondEntityColumns.contains("city"), "e2 should have 'city'");

        // 验证两个列集不相等（这就是修复前抛异常的原因）
        assertNotEquals(firstEntityColumns, secondEntityColumns,
            "Column sets should differ, causing the old code to throw");
    }

    /**
     * 验证 null @Embedded 的实体在列提取时正确跳过子字段。
     */
    @Test
    void extractFieldValues_nullEmbedded_skipsSubFields() {
        EntityFieldExtractor<BatchEmbeddedEntity> extractor =
            new EntityFieldExtractor<>(BatchEmbeddedEntity.class);

        BatchEmbeddedEntity entity = new BatchEmbeddedEntity();
        entity.setName("Test");
        entity.setAddress(null);

        List<EntityFieldExtractor.EntityFieldValue> fields = extractor.extractFieldValues(entity);

        // 不应包含 address 子字段
        assertFalse(fields.stream().anyMatch(f -> f.columnName().equals("street")),
            "Null embedded should not produce 'street' column");
        assertFalse(fields.stream().anyMatch(f -> f.columnName().equals("city")),
            "Null embedded should not produce 'city' column");

        // 应包含 name 字段
        assertTrue(fields.stream().anyMatch(f -> f.columnName().equals("name")),
            "Should contain 'name' column");
    }

    /**
     * 验证非 null @Embedded 的实体在列提取时包含子字段。
     */
    @Test
    void extractFieldValues_nonNullEmbedded_includesSubFields() {
        EntityFieldExtractor<BatchEmbeddedEntity> extractor =
            new EntityFieldExtractor<>(BatchEmbeddedEntity.class);

        BatchEmbeddedEntity entity = new BatchEmbeddedEntity();
        entity.setName("Test");
        entity.setAddress(new Address("123 Main St", "NYC"));

        List<EntityFieldExtractor.EntityFieldValue> fields = extractor.extractFieldValues(entity);

        // 应包含 address 子字段
        assertTrue(fields.stream().anyMatch(f -> f.columnName().equals("street")),
            "Non-null embedded should produce 'street' column");
        assertTrue(fields.stream().anyMatch(f -> f.columnName().equals("city")),
            "Non-null embedded should produce 'city' column");
        assertTrue(fields.stream().anyMatch(f -> f.columnName().equals("name")),
            "Should contain 'name' column");
    }
}
